# Copyright 2011-2013, Dell
# Copyright 2013, SUSE LINUX Products GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Dell Crowbar Team
# Author: SUSE LINUX Products GmbH
#

source "https://rubygems.org"

gem "rails", "2.3.17"
gem "haml", "3.1.6"
gem "sass", "3.2.12"
gem "simple-navigation", "3.7.0"
gem "i18n", "0.4.2"
gem "json", "1.6.1"
gem "chef", "10.24.4"
gem "app_config", "1.0.2"
gem "mime-types", "1.23"

# Needed when running in production environment
gem "syslogger"
gem "kwalify"

# Adds the asset pipeline to process js and css
gem "sprockets", "2.10.1"
gem "tilt", "1.3.3"
gem "hike", "1.2.1"
gem "multi_json", "1.0.3"
gem "rack", "1.1.6"
gem "sprockets-sass", "1.0.2"
gem "sprockets-helpers", "1.1.0"

group :development do
  gem "brakeman"
end

# Install gems from each barclamp. The crowbar_path variable is
# needed by Gemfile.d/*.gemfile so that they can determine the correct
# path at run-time rather than having to hard-code a path at
# install-time which may be different and therefore incorrect.
crowbar_path = File.expand_path("..", __FILE__)
Dir.glob(File.join(crowbar_path, "Gemfile.d", "*.gemfile")) do |gemfile|
  eval(IO.read(gemfile), binding)
end
