source "https://rubygems.org"

gem "rails", "2.3.12"
gem "haml"
gem "sass"
gem "simple-navigation"
gem "i18n"
gem "json"
gem "chef"
gem "thin"
gem "formtastic"

group :development do
  # bundler requires these gems in development
  # gem "rails-footnotes"
end

group :test do
  # bundler requires these gems while running tests
  # gem "rspec"
  # gem "faker"
end

