source "https://rubygems.org"

gem "rails", "2.3.18"
gem "haml",  "3.1.6"
gem "sass",  "3.1.2"
gem "simple-navigation", "3.7.0"
gem "i18n",  "0.4.2"
gem "json",  "1.6.1"
gem "chef",  "10.24.4"
gem "app_config", "1.0.2"

# Needed when running in production environment
gem "syslogger"
gem "kwalify"

group :development do
  # bundler requires these gems in development
  # gem "rails-footnotes"
  gem "brakeman"
end

group :test do
  # bundler requires these gems while running tests
  # gem "rspec"
  # gem "faker"
end
