#!/bin/bash
export PS4='${BASH_SOURCE}@${LINENO}(${FUNCNAME[0]}): '
set -x
export TMPDIR=$1
export ROLE=$2

# To force dpkg on Debian-based distros to play nice.
export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
export LC_ALL=C LANGUAGE=C LANG=C

read_attribute() {
    if [[ -f $TMPDIR/attrs/$1/attr ]]; then
        cat "$TMPDIR/attrs/$1/attr"
    else
        echo ""
    fi
}

write_attribute() {
    local loc="$TMPDIR/attrs/$1"
    mkdir -p "$loc"
    printf "%s" "$2" > "$loc/wall"
}

mkdir -p "$TMPDIR/attrs"

for script in "$TMPDIR/$ROLE/"*.sh; do
    ( . "$script" ) || exit $?
done
exit 0
