name "utils"
maintainer "Crowbar Project"
maintainer_email "crowbar@googlegroups.com"
license "Apache 2.0"
description "Provides utilities for other recipes: line"
long_description "Provides utilities for other recipes: line"
version "0.9.5"
