#!/bin/bash
# chkconfig: 2345 10 90
# description: Bluepill Daemon runner
PATH=$PATH:/usr/local/bin:/usr/local/sbin
case $1 in
    start) for pill in /etc/bluepill/*.pill; do
        [[ -f $pill ]] || continue
        bluepill load "$pill"
        done;;
    stop|restart) echo "Stop is not implemented, since bluepill processes are run independently.";;
    status) 
	if ps aux |grep -q [b]luepilld; then
            echo "Bluepill is running."
	    bluepill status
            exit 0
        else
            echo "Bluepill is not running."
            exit 1
        fi;;
    ''|"help")
	echo "$0: Bluepill init script"
	echo "Supported options:"
	echo "    start:   Starts a bluepill for any .pills in /etc/bluepill."
	echo "    status:  Shows the status of running bluepills."
	echo "    stop:    Not supported.  Use bluepill directly to stop a process."
	echo "    restart: Not supported for the same reason that stop is not supported."
	echo "    help:    This message." ;;
    *) 
	echo "Assuming you meant $(which bluepill)."
	exec bluepill "$@";;
esac
