#!/bin/bash
## only do this on real installs.
[[  -d /tftpboot/ubuntu_dvd/dell/Version || \
    -d /tftpboot/redhat_dvd/dell/Version || \
    -d /opt/dell/barclamps/crowbar ]] || \
    { echo "Not an admin node, not creating machine key"; exit 0; }

if [[ ! -e /etc/crowbar.install.key ]]; then
    dd if=/dev/urandom bs=65536 count=1 2>/dev/null |sha512sum - 2>/dev/null | \
        (read key rest; echo "machine-install:$key" >/etc/crowbar.install.key)
fi
